import 'package:flutter/material.dart';
import 'package:my_portfolio/models/selected_works_model.dart';
import 'package:my_portfolio/utilities/app_images.dart';

class SelectedProjectData {
  static List<SelectedProjectModel> selectedProjects = [
    SelectedProjectModel(
      index: 0,
      mainImage: AppImages.hmk1,
      secondImage: AppImages.hmk2,
      thirdImage: AppImages.hmk3,
      mainImageBG: Colors.black,
      secondImageBG: Colors.black,
      thirdImageBG: Colors.black,
      title: '10thbit',
      company: 'Software Company',
      projectDate: 'March 2023',
      projectType: 'Website Development',
      projectDuration: '2 months',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      challengesFaced:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      results:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      extraImage1: AppImages.hmk4,
      extraImage2: AppImages.hmk5,
      extraImage3: 'null',
      extraImage4: 'null',
      extraImage5: 'null',
      extraImage6: 'null',
      extraImage7: 'null',
      extraImage8: 'null',
      extraImage9: 'null',
      extraImage10: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      index: 1,
      mainImage: AppImages.artache1,
      secondImage: AppImages.artache2,
      thirdImage: AppImages.artache3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Artache Magazine',
      company: 'Digital Magazine',
      projectDate: 'September 2023',
      projectType: 'Digital Web Magazine',
      projectDuration: '5 months',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette.',
      challengesFaced:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      results:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      extraImage1: AppImages.artache4,
      extraImage2: AppImages.artache5,
      extraImage3: AppImages.artache6,
      extraImage4: AppImages.artache7,
      extraImage5: AppImages.artache8,
      extraImage6: AppImages.artache9,
      extraImage7: AppImages.artache10,
      extraImage8: AppImages.artache11,
      extraImage9: 'null',
      extraImage10: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      index: 2,
      mainImage: AppImages.bridges1,
      secondImage: AppImages.bridges2,
      thirdImage: AppImages.bridges3,
      mainImageBG: Colors.black,
      secondImageBG: Colors.black,
      thirdImageBG: Colors.black,
      title: 'Bridges Interactive',
      company: 'Gaming Portfolio',
      projectDate: 'January 2022',
      projectType: 'Web Application',
      projectDuration: '4 months',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette.',
      challengesFaced:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      results:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      extraImage1: AppImages.bridges4,
      extraImage2: 'null',
      extraImage3: 'null',
      extraImage4: 'null',
      extraImage5: 'null',
      extraImage6: 'null',
      extraImage7: 'null',
      extraImage8: 'null',
      extraImage9: 'null',
      extraImage10: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      index: 3,
      mainImage: AppImages.barak1,
      secondImage: AppImages.barak2,
      thirdImage: AppImages.barak3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Barak IP',
      company: 'Intellectual Law Firm',
      projectDate: 'October 2021',
      projectType: 'Corporation Website',
      projectDuration: '1 month',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      challengesFaced:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      results:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      extraImage1: AppImages.barak4,
      extraImage2: AppImages.barak5,
      extraImage3: AppImages.barak6,
      extraImage4: AppImages.barak7,
      extraImage5: 'null',
      extraImage6: 'null',
      extraImage7: 'null',
      extraImage8: 'null',
      extraImage9: 'null',
      extraImage10: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      index: 4,
      mainImage: AppImages.andres1,
      secondImage: AppImages.andres2,
      thirdImage: AppImages.andres3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Andreas Steinkogler',
      company: 'Intellectual Law Firm',
      projectDate: 'October 2021',
      projectType: 'Corporation Website',
      projectDuration: '1 month',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      challengesFaced:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      results:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      extraImage1: AppImages.andres4,
      extraImage2: AppImages.andres5,
      extraImage3: AppImages.andres6,
      extraImage4: AppImages.andres7,
      extraImage5: 'null',
      extraImage6: 'null',
      extraImage7: 'null',
      extraImage8: 'null',
      extraImage9: 'null',
      extraImage10: 'null',
      mobileView: 'null',
    ),
  ];
}
