import 'package:flutter/material.dart';
import 'package:my_portfolio/models/selected_works_model.dart';
import 'package:my_portfolio/utilities/app_images.dart';

class SelectedProjectData {
  static List<SelectedProjectModel> selectedWebProjects = [
    SelectedProjectModel(
      index: 0,
      mainImage: AppImages.hmk1,
      secondImage: AppImages.hmk2,
      thirdImage: AppImages.hmk3,
      mainImageBG: Colors.black,
      secondImageBG: Colors.black,
      thirdImageBG: Colors.black,
      title: 'HMK',
      company: 'Hamza Majeed Khan',
      projectDate: 'March 2022',
      projectType: 'Portfolio Development',
      projectDuration: '2 months',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'In the vibrant realm of digital design, our development team embarked on a journey to establish a compelling online showcase for a distinguished designer and artist. Our mission was to encapsulate the essence of creativity and professionalism, curating a platform that not only mirrored the artist\'s vision but also delivered a seamless and captivating user experience. This case study unravels the complexities we encountered, the innovative strategies we employed, and the resounding success we achieved in elevating the digital presence of our esteemed client.',
      challengesFaced:
          'To address the array of challenges, our development team embraced a multifaceted strategy. Initiating with extensive consultations, we collaborated closely with the client to discern their unique strengths, showcase key projects, and pinpoint the target audience. Guided by a user-centric design philosophy, we meticulously crafted an intuitive navigation system, categorizing projects by type and scale. Incorporating dynamic visual elements such as high-quality images and interactive project timelines, we aimed to captivate visitors and offer an immersive exploration. Amidst challenges like integrating data from external sources and addressing theme issues to meet the discerning eye of an artist, our team remained steadfast. Additionally, prioritizing seamless accessibility, we devoted meticulous attention to optimizing the website for responsiveness across all devices, ensuring a seamless browsing experience for users spanning desktops, tablets, and smartphones.',
      results:
          'Despite the hurdles faced, the project achieved remarkable success, presenting a professional and cohesive presentation of Hamza\'s artistic journey. The website\'s launch has garnered positive feedback, effectively showcasing Hamza\'s skills and achievements to a wider audience, thereby enhancing his visibility and recognition within the creative industry.',
      extraImage1: AppImages.hmk4,
      extraImage2: AppImages.hmk5,
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.white,
      builtForAndroid: false,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 1,
      mainImage: AppImages.artache1,
      secondImage: AppImages.artache2,
      thirdImage: AppImages.artache4,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Artache Magazine',
      company: 'Digital Magazine',
      projectDate: 'September 2023',
      projectType: 'Digital Web Magazine',
      projectDuration: '6 months',
      shortBio:
          'Digitally elevating artistry, extending its global reach professionally',
      description:
          'Artache Magazine is a pioneering digital platform at the forefront of the local industry, merging the worlds of art and literature into an innovative digital magazine format. It serves as a global showcase for artists and writers, providing a dynamic space for them to share their creative endeavors with a diverse audience. Through its digital medium, Artache Magazine aims to elevate the appreciation of art while fostering creativity and collaboration.',
      challengesFaced:
          'Navigating the creation of Artache Magazine posed several challenges. Firstly, identifying and engaging the target audience presented a significant hurdle, as we aimed to appeal to a broad demographic of art and literature enthusiasts. Secondly, sourcing content from artists worldwide proved to be a logistical challenge, requiring extensive outreach and coordination. Additionally, implementing a technical infrastructure capable of managing the influx of diverse content while ensuring a seamless user experience presented its own set of complexities.',
      results:
          'Despite these challenges, Artache Magazine has achieved remarkable success since its inception. The platform has successfully curated an extensive collection of artwork and literary pieces from artists around the globe, providing a vibrant showcase for creative expression. Its launch has sparked a newfound enthusiasm for art and literature, fostering a global community of creators and enthusiasts. Artache Magazine continues to make a positive impact by amplifying the voices of artists and writers worldwide and pushing the boundaries of digital creativity.',
      extraImage1: AppImages.artache4,
      extraImage2: AppImages.artache5,
      extraImage3: AppImages.artache6,
      extraImage4: AppImages.artache7,
      extraImage5: AppImages.artache8,
      extraImage6: AppImages.artache9,
      extraImage7: AppImages.artache10,
      extraImage8: AppImages.artache3,
      extraImage9: AppImages.artache11,
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.white,
      builtForAndroid: false,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 2,
      mainImage: AppImages.andres1,
      secondImage: AppImages.andres2,
      thirdImage: AppImages.andres3,
      mainImageBG: Colors.black,
      secondImageBG: Colors.black,
      thirdImageBG: Colors.white,
      title: 'Andreas Steinkogler',
      company: 'Filmmaker',
      projectDate: 'October 2020',
      projectType: 'Portfolio Website',
      projectDuration: '2 months',
      shortBio:
          'Step into Steinkogler\'s world of impactful filmmaking and composition',
      description:
          'The Andreas Steinkogler website stands as a testament to creative versatility and professional prowess. Through a seamless integration of artistic vision and technical expertise, it serves as an immersive portal into Andreas\'s multifaceted talents and offerings. From captivating films to visually stunning artworks, the website encapsulates the breadth and depth of Andreas\'s creative portfolio, inviting visitors to explore and engage with his diverse range of services.',
      challengesFaced:
          'In the creation of Andreas Steinkogler\'s website, several challenges emerged, requiring innovative solutions and meticulous attention to detail. Chief among these challenges was the task of effectively delivering Andreas\'s capabilities to the targeted audience. Additionally, integrating samples of Andreas\'s work into the website while maintaining professional aesthetics and showcasing a diverse range of client projects from around the globe posed logistical hurdles. Despite these challenges, the project team remained steadfast, ultimately overcoming obstacles to deliver a polished and impactful digital platform.',
      results:
          'The launch of the Andreas Steinkogler website has yielded significant results, establishing a professional online presence for Andreas and garnering positive feedback from audiences worldwide. The website\'s immersive design and seamless navigation have facilitated increased visibility and recognition within the film industry and beyond. Moreover, the platform has fostered fruitful collaborations and opportunities, connecting Andreas with clients from diverse backgrounds and geographical locations. As a testament to its success, the website continues to serve as a vibrant hub for creative expression and professional services in the realms of filmmaking and visual artistry.',
      extraImage1: AppImages.andres4,
      extraImage2: AppImages.andres5,
      extraImage3: AppImages.andres6,
      extraImage4: AppImages.andres7,
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.white,
      builtForAndroid: false,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 3,
      mainImage: AppImages.barak1,
      secondImage: AppImages.barak2,
      thirdImage: AppImages.barak3,
      mainImageBG: Colors.black,
      secondImageBG: Colors.black,
      thirdImageBG: Colors.black,
      title: 'Barak IP',
      company: 'Intellectual Law Firm',
      projectDate: 'October 2021',
      projectType: 'Corporate Website',
      projectDuration: '1 month',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: AppImages.barak4,
      extraImage2: AppImages.barak5,
      extraImage3: AppImages.barak6,
      extraImage4: AppImages.barak7,
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.white,
      builtForAndroid: false,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 4,
      mainImage: AppImages.bridges1,
      secondImage: AppImages.bridges2,
      thirdImage: AppImages.bridges3,
      mainImageBG: Colors.black,
      secondImageBG: Colors.black,
      thirdImageBG: Colors.black,
      title: 'Bridges Interactive',
      company: 'Gaming Portfolio',
      projectDate: 'January 2022',
      projectType: 'Website Development',
      projectDuration: '2 months',
      shortBio: 'Connecting games with users through innovative platforms',
      description:
          'The website serves as a central hub for showcasing their diverse game library, announcing upcoming releases, and engaging with gaming enthusiasts worldwide. With a commitment to excellence and innovation, Bridges Interactive strives to deliver immersive gaming experiences that captivate and inspire players of all ages.',
      challengesFaced:
          'During development, Bridges Interactive encountered several hurdles. These included ensuring that announcements regarding new games and titles reached a global audience effectively. Additionally, expanding the reach and visibility of Bridges Interactive to foster growth and engagement proved to be a significant challenge. Moreover, providing seamless access to their games through their proprietary platform while ensuring user convenience and satisfaction posed another obstacle to overcome.',
      results:
          'Despite these challenges, the launch of the Bridges Interactive website has yielded significant results, bolstering the company\'s online presence and fostering engagement within the gaming community. The website\'s positive growth impact has led to increased visibility and recognition, resulting in expanded opportunities for Bridges Interactive. Additionally, by providing seamless access to their games through their proprietary platform, Bridges Interactive has enhanced the gaming experience for users while ensuring convenience and satisfaction.',
      extraImage1: AppImages.bridges4,
      extraImage2: '',
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.white,
      builtForAndroid: false,
      builtForApple: false,
    ),
  ];

  static List<SelectedProjectModel> selectedMobileProjects = [
    SelectedProjectModel(
      index: 0,
      mainImage: AppImages.restofe1,
      secondImage: AppImages.restofe2,
      thirdImage: AppImages.restofe3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Restofe',
      company: 'Gourmet Gulf',
      projectDate: 'March 2022',
      projectType: 'App Development',
      projectDuration: '3 months',
      shortBio:
          'Utilizing captivating imagery to enhance the overall user experience',
      description:
          'In the vibrant realm of digital design, our development team embarked on a journey to establish a compelling online showcase for a distinguished designer and artist. Our mission was to encapsulate the essence of creativity and professionalism, curating a platform that not only mirrored the artist\'s vision but also delivered a seamless and captivating user experience. This case study unravels the complexities we encountered, the innovative strategies we employed, and the resounding success we achieved in elevating the digital presence of our esteemed client.',
      challengesFaced:
          'To address the array of challenges, our development team embraced a multifaceted strategy. Initiating with extensive consultations, we collaborated closely with the client to discern their unique strengths, showcase key projects, and pinpoint the target audience. Guided by a user-centric design philosophy, we meticulously crafted an intuitive navigation system, categorizing projects by type and scale. Incorporating dynamic visual elements such as high-quality images and interactive project timelines, we aimed to captivate visitors and offer an immersive exploration. Amidst challenges like integrating data from external sources and addressing theme issues to meet the discerning eye of an artist, our team remained steadfast. Additionally, prioritizing seamless accessibility, we devoted meticulous attention to optimizing the website for responsiveness across all devices, ensuring a seamless browsing experience for users spanning desktops, tablets, and smartphones.',
      results:
          'Despite the hurdles faced, the project achieved remarkable success, presenting a professional and cohesive presentation of Hamza\'s artistic journey. The website\'s launch has garnered positive feedback, effectively showcasing Hamza\'s skills and achievements to a wider audience, thereby enhancing his visibility and recognition within the creative industry.',
      extraImage1: AppImages.restofe4,
      extraImage2: AppImages.restofe5,
      extraImage3: AppImages.restofe6,
      extraImage4: AppImages.restofe7,
      extraImage5: AppImages.restofe8,
      extraImage6: AppImages.restofe9,
      extraImage7: AppImages.restofe10,
      extraImage8: AppImages.restofe11,
      extraImage9: AppImages.restofe12,
      extraImage10: AppImages.restofe13,
      extraImage11: AppImages.restofe14,
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.blue.shade900,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 1,
      mainImage: AppImages.mask1,
      secondImage: AppImages.mask2,
      thirdImage: AppImages.mask3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Mask Reminder',
      company: '10thbit',
      projectDate: 'September 2023',
      projectType: 'App Development',
      projectDuration: '6 months',
      shortBio:
          'Digitally elevating artistry, extending its global reach professionally',
      description:
          'Artache Magazine is a pioneering digital platform at the forefront of the local industry, merging the worlds of art and literature into an innovative digital magazine format. It serves as a global showcase for artists and writers, providing a dynamic space for them to share their creative endeavors with a diverse audience. Through its digital medium, Artache Magazine aims to elevate the appreciation of art while fostering creativity and collaboration.',
      challengesFaced:
          'Navigating the creation of Artache Magazine posed several challenges. Firstly, identifying and engaging the target audience presented a significant hurdle, as we aimed to appeal to a broad demographic of art and literature enthusiasts. Secondly, sourcing content from artists worldwide proved to be a logistical challenge, requiring extensive outreach and coordination. Additionally, implementing a technical infrastructure capable of managing the influx of diverse content while ensuring a seamless user experience presented its own set of complexities.',
      results:
          'Despite these challenges, Artache Magazine has achieved remarkable success since its inception. The platform has successfully curated an extensive collection of artwork and literary pieces from artists around the globe, providing a vibrant showcase for creative expression. Its launch has sparked a newfound enthusiasm for art and literature, fostering a global community of creators and enthusiasts. Artache Magazine continues to make a positive impact by amplifying the voices of artists and writers worldwide and pushing the boundaries of digital creativity.',
      extraImage1: AppImages.mask4,
      extraImage2: AppImages.mask5,
      extraImage3: AppImages.mask6,
      extraImage4: AppImages.mask7,
      extraImage5: AppImages.mask8,
      extraImage6: AppImages.mask9,
      extraImage7: AppImages.mask10,
      extraImage8: AppImages.mask11,
      extraImage9: AppImages.mask12,
      extraImage10: AppImages.mask13,
      extraImage11: AppImages.mask14,
      extraImage12: AppImages.mask15,
      extraImage13: AppImages.mask16,
      extraImage14: AppImages.mask17,
      extraImage15: AppImages.mask18,
      extraImage16: AppImages.mask19,
      extraImage17: AppImages.mask20,
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.indigo,
      builtForAndroid: true,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 2,
      mainImage: AppImages.calorie1,
      secondImage: AppImages.calorie2,
      thirdImage: AppImages.calorie3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Calorie Counter',
      company: '10thbit',
      projectDate: 'October 2020',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio:
          'Step into Steinkogler\'s world of impactful filmmaking and composition',
      description:
          'The Andreas Steinkogler website stands as a testament to creative versatility and professional prowess. Through a seamless integration of artistic vision and technical expertise, it serves as an immersive portal into Andreas\'s multifaceted talents and offerings. From captivating films to visually stunning artworks, the website encapsulates the breadth and depth of Andreas\'s creative portfolio, inviting visitors to explore and engage with his diverse range of services.',
      challengesFaced:
          'In the creation of Andreas Steinkogler\'s website, several challenges emerged, requiring innovative solutions and meticulous attention to detail. Chief among these challenges was the task of effectively delivering Andreas\'s capabilities to the targeted audience. Additionally, integrating samples of Andreas\'s work into the website while maintaining professional aesthetics and showcasing a diverse range of client projects from around the globe posed logistical hurdles. Despite these challenges, the project team remained steadfast, ultimately overcoming obstacles to deliver a polished and impactful digital platform.',
      results:
          'The launch of the Andreas Steinkogler website has yielded significant results, establishing a professional online presence for Andreas and garnering positive feedback from audiences worldwide. The website\'s immersive design and seamless navigation have facilitated increased visibility and recognition within the film industry and beyond. Moreover, the platform has fostered fruitful collaborations and opportunities, connecting Andreas with clients from diverse backgrounds and geographical locations. As a testament to its success, the website continues to serve as a vibrant hub for creative expression and professional services in the realms of filmmaking and visual artistry.',
      extraImage1: AppImages.calorie4,
      extraImage2: AppImages.calorie5,
      extraImage3: AppImages.calorie6,
      extraImage4: AppImages.calorie7,
      extraImage5: AppImages.calorie8,
      extraImage6: AppImages.calorie9,
      extraImage7: AppImages.calorie10,
      extraImage8: AppImages.calorie11,
      extraImage9: AppImages.calorie12,
      extraImage10: AppImages.calorie13,
      extraImage11: AppImages.calorie14,
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.indigoAccent.shade200,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 3,
      mainImage: AppImages.translator1,
      secondImage: AppImages.translator2,
      thirdImage: AppImages.translator3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Language Translator',
      company: '10thbit',
      projectDate: 'July 2020',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: AppImages.translator4,
      extraImage2: AppImages.translator5,
      extraImage3: AppImages.translator6,
      extraImage4: AppImages.translator7,
      extraImage5: AppImages.translator8,
      extraImage6: AppImages.translator9,
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.blue,
      builtForAndroid: true,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 4,
      mainImage: AppImages.vp1,
      secondImage: AppImages.vp2,
      thirdImage: AppImages.vp3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Sind Corporation Vehicle Portal',
      company: 'Sind Corporation',
      projectDate: 'September 2023',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: AppImages.vp4,
      extraImage2: AppImages.vp5,
      extraImage3: AppImages.vp6,
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.green.shade800,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 5,
      mainImage: AppImages.ap1,
      secondImage: AppImages.ap2,
      thirdImage: AppImages.ap3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Sind Corporation Admin Portal',
      company: 'Sind Corporation',
      projectDate: 'September 2023',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: AppImages.ap4,
      extraImage2: AppImages.ap5,
      extraImage3: AppImages.ap6,
      extraImage4: AppImages.ap7,
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.green.shade800,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 6,
      mainImage: AppImages.sms1,
      secondImage: AppImages.sms2,
      thirdImage: AppImages.sms3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Sind Corporation SMS Portal',
      company: 'Sind Corporation',
      projectDate: 'September 2023',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: AppImages.sms4,
      extraImage2: AppImages.sms5,
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.indigo.shade900,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 7,
      mainImage: AppImages.gdsc1,
      secondImage: AppImages.gdsc2,
      thirdImage: AppImages.gdsc3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'GDSC',
      company: 'Google Developers Student Club',
      projectDate: 'October 2021',
      projectType: 'App Development',
      projectDuration: '1 month',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: AppImages.gdsc4,
      extraImage2: AppImages.gdsc5,
      extraImage3: AppImages.gdsc6,
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.red,
      builtForAndroid: true,
      builtForApple: false,
    ),
    SelectedProjectModel(
      index: 8,
      mainImage: AppImages.dock1,
      secondImage: AppImages.dock2,
      thirdImage: '',
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Dock Management',
      company: '10thbit',
      projectDate: 'January 2022',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio: 'Connecting games with users through innovative platforms',
      description:
          'The website serves as a central hub for showcasing their diverse game library, announcing upcoming releases, and engaging with gaming enthusiasts worldwide. With a commitment to excellence and innovation, Bridges Interactive strives to deliver immersive gaming experiences that captivate and inspire players of all ages.',
      challengesFaced:
          'During development, Bridges Interactive encountered several hurdles. These included ensuring that announcements regarding new games and titles reached a global audience effectively. Additionally, expanding the reach and visibility of Bridges Interactive to foster growth and engagement proved to be a significant challenge. Moreover, providing seamless access to their games through their proprietary platform while ensuring user convenience and satisfaction posed another obstacle to overcome.',
      results:
          'Despite these challenges, the launch of the Bridges Interactive website has yielded significant results, bolstering the company\'s online presence and fostering engagement within the gaming community. The website\'s positive growth impact has led to increased visibility and recognition, resulting in expanded opportunities for Bridges Interactive. Additionally, by providing seamless access to their games through their proprietary platform, Bridges Interactive has enhanced the gaming experience for users while ensuring convenience and satisfaction.',
      extraImage1: '',
      extraImage2: '',
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.blue,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 9,
      mainImage: AppImages.climate1,
      secondImage: AppImages.climate2,
      thirdImage: AppImages.climate3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Climate',
      company: '10thbit',
      projectDate: 'January 2022',
      projectType: 'App Development',
      projectDuration: '2 months',
      shortBio: 'Connecting games with users through innovative platforms',
      description:
          'The website serves as a central hub for showcasing their diverse game library, announcing upcoming releases, and engaging with gaming enthusiasts worldwide. With a commitment to excellence and innovation, Bridges Interactive strives to deliver immersive gaming experiences that captivate and inspire players of all ages.',
      challengesFaced:
          'During development, Bridges Interactive encountered several hurdles. These included ensuring that announcements regarding new games and titles reached a global audience effectively. Additionally, expanding the reach and visibility of Bridges Interactive to foster growth and engagement proved to be a significant challenge. Moreover, providing seamless access to their games through their proprietary platform while ensuring user convenience and satisfaction posed another obstacle to overcome.',
      results:
          'Despite these challenges, the launch of the Bridges Interactive website has yielded significant results, bolstering the company\'s online presence and fostering engagement within the gaming community. The website\'s positive growth impact has led to increased visibility and recognition, resulting in expanded opportunities for Bridges Interactive. Additionally, by providing seamless access to their games through their proprietary platform, Bridges Interactive has enhanced the gaming experience for users while ensuring convenience and satisfaction.',
      extraImage1: AppImages.climate4,
      extraImage2: '',
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.black87,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 10,
      mainImage: AppImages.counter1,
      secondImage: AppImages.counter2,
      thirdImage: AppImages.counter3,
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Counter',
      company: '10thbit',
      projectDate: 'April 2022',
      projectType: 'App Development',
      projectDuration: '1 month',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: '',
      extraImage2: '',
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.black,
      builtForAndroid: true,
      builtForApple: true,
    ),
    SelectedProjectModel(
      index: 11,
      mainImage: AppImages.calculator1,
      secondImage: AppImages.calculator1,
      thirdImage: '',
      mainImageBG: Colors.white,
      secondImageBG: Colors.white,
      thirdImageBG: Colors.white,
      title: 'Calculator',
      company: '10thbit',
      projectDate: 'January 2021',
      projectType: 'App Development',
      projectDuration: '1 month',
      shortBio:
          'Championing renowned brands, safeguarding their intellectual property rights',
      description:
          'At the forefront of intellectual property law, Barak IP is dedicated to safeguarding the creative and innovative assets of individuals and businesses globally. With a focus on excellence and client-centered service, the firm offers tailored solutions to protect and enforce intellectual property rights.',
      challengesFaced:
          'In establishing its online presence, Barak IP encountered various obstacles, including attracting a diverse client base and effectively communicating its specialized services. Educating prospective clients about the significance of intellectual property rights and the firm\'s role proved to be crucial challenges.',
      results:
          'Despite these hurdles, the launch of the Barak IP website has yielded significant results, reinforcing the firm\'s reputation as a trusted legal partner. The website\'s intuitive design and informative content have enhanced visibility within the legal community, garnering praise and fostering meaningful connections. Barak IP continues to make a profound impact by championing intellectual property rights and empowering clients to thrive in an ever-evolving landscape.',
      extraImage1: '',
      extraImage2: '',
      extraImage3: '',
      extraImage4: '',
      extraImage5: '',
      extraImage6: '',
      extraImage7: '',
      extraImage8: '',
      extraImage9: '',
      extraImage10: '',
      extraImage11: '',
      extraImage12: '',
      extraImage13: '',
      extraImage14: '',
      extraImage15: '',
      extraImage16: '',
      extraImage17: '',
      mobileView: '',
      appIcon: '',
      appThemeColor: Colors.black,
      builtForAndroid: true,
      builtForApple: true,
    ),
  ];

  static List<SelectedProjectModel> selectedHybridProjects = [];
}
