import 'package:my_portfolio/models/selected_works_model.dart';

class SelectedProjectData {
  static List<SelectedProjectModel> selectedProjects = [
    SelectedProjectModel(
      mainImage: 'assets/showcase/hmk1.png',
      secondImage: 'assets/showcase/hmk1.png',
      thirdImage: 'assets/showcase/hmk1.png',
      title: '10thbit',
      company: 'Software Company',
      projectDate: 'March 2023',
      projectType: 'null',
      projectDuration: 'null',
      shortBio: 'null',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      challengesFaced: 'null',
      results: 'null',
      extraImage1: 'null',
      extraImage2: 'null',
      extraImage3: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      mainImage: 'assets/showcase/art1.png',
      secondImage: 'assets/showcase/art1.png',
      thirdImage: 'assets/showcase/art1.png',
      title: 'Artache Magazine',
      company: 'Digital Magazine',
      projectDate: 'September 2023',
      projectType: 'null',
      projectDuration: 'null',
      shortBio: 'null',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience. This exploration centers on crafting an engaging layout, selecting an appealing color palette.',
      challengesFaced: 'null',
      results: 'null',
      extraImage1: 'null',
      extraImage2: 'null',
      extraImage3: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      mainImage: 'assets/showcase/art1.png',
      secondImage: 'assets/showcase/art1.png',
      thirdImage: 'assets/showcase/art1.png',
      title: 'Bridges Interactive',
      company: 'Gaming Portfolio',
      projectDate: 'January 2022',
      projectType: 'null',
      projectDuration: 'null',
      shortBio: 'null',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette.',
      challengesFaced: 'null',
      results: 'null',
      extraImage1: 'null',
      extraImage2: 'null',
      extraImage3: 'null',
      mobileView: 'null',
    ),
    SelectedProjectModel(
      mainImage: 'assets/showcase/barak1.png',
      secondImage: 'assets/showcase/barak1.png',
      thirdImage: 'assets/showcase/barak1.png',
      title: 'Barak IP',
      company: 'Intellectual Law Firm',
      projectDate: 'October 2021',
      projectType: 'null',
      projectDuration: 'null',
      shortBio: 'null',
      description:
          'This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.This exploration centers on crafting an engaging layout, selecting an appealing color palette, and utilizing captivating imagery to enhance the overall user experience.',
      challengesFaced: 'null',
      results: 'null',
      extraImage1: 'null',
      extraImage2: 'null',
      extraImage3: 'null',
      mobileView: 'null',
    ),
  ];
}
