// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-ptU89XEHnaPEt-_9pFkQPJIpHp42qA',
    appId: '1:1049233353597:web:e0acf4fe590dd548933a14',
    messagingSenderId: '1049233353597',
    projectId: 'myportfolio-d8c86',
    authDomain: 'myportfolio-d8c86.firebaseapp.com',
    storageBucket: 'myportfolio-d8c86.appspot.com',
    measurementId: 'G-YMQH3HN43N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSMcWi7wQ2u2UcKWSzAHlrP0OyUxLJE4',
    appId: '1:1049233353597:android:a026a0211ccdcf7d933a14',
    messagingSenderId: '1049233353597',
    projectId: 'myportfolio-d8c86',
    storageBucket: 'myportfolio-d8c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGj_pDfItV4LPEuf_jzdi3AvNfHk67qo',
    appId: '1:1049233353597:ios:483dc617566e2248933a14',
    messagingSenderId: '1049233353597',
    projectId: 'myportfolio-d8c86',
    storageBucket: 'myportfolio-d8c86.appspot.com',
    iosBundleId: 'com.faisal.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGj_pDfItV4LPEuf_jzdi3AvNfHk67qo',
    appId: '1:1049233353597:ios:483dc617566e2248933a14',
    messagingSenderId: '1049233353597',
    projectId: 'myportfolio-d8c86',
    storageBucket: 'myportfolio-d8c86.appspot.com',
    iosBundleId: 'com.faisal.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg-ptU89XEHnaPEt-_9pFkQPJIpHp42qA',
    appId: '1:1049233353597:web:3c50f65727928b82933a14',
    messagingSenderId: '1049233353597',
    projectId: 'myportfolio-d8c86',
    authDomain: 'myportfolio-d8c86.firebaseapp.com',
    storageBucket: 'myportfolio-d8c86.appspot.com',
    measurementId: 'G-EQTV1ZBW4X',
  );
}
